
-- Create bookings table if missing
CREATE TABLE IF NOT EXISTS bookings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id uuid REFERENCES users(id),
  company_car_id bigint REFERENCES company_cars(id),
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone NOT NULL,
  total_amount numeric,
  status text DEFAULT 'pending',
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS payment_statuses (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  value integer NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS payment_types (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now()
);

-- Truncate tables to remove invalid data
TRUNCATE TABLE payments, contracts RESTART IDENTITY CASCADE;

-- Fix structure of 'contracts' table
-- First, drop existing inaccurate constraints if any (to avoid conflicts)
DO $$ 
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'contracts_user_id_fkey') THEN
        ALTER TABLE contracts DROP CONSTRAINT contracts_user_id_fkey;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'contracts_car_id_fkey') THEN
        ALTER TABLE contracts DROP CONSTRAINT contracts_car_id_fkey;
    END IF;
END $$;

-- Rename columns to match application code
ALTER TABLE contracts RENAME COLUMN car_id TO company_car_id;
ALTER TABLE contracts RENAME COLUMN user_id TO client_id;

-- Add missing columns
ALTER TABLE contracts 
    ADD COLUMN IF NOT EXISTS manager_id uuid,
    ADD COLUMN IF NOT EXISTS booking_id bigint,
    ADD COLUMN IF NOT EXISTS deposit_amount numeric,
    ADD COLUMN IF NOT EXISTS notes text;

-- Add Foreign Key Constraints with specific names used in code
ALTER TABLE contracts
    ADD CONSTRAINT contracts_company_car_id_fkey FOREIGN KEY (company_car_id) REFERENCES company_cars(id),
    ADD CONSTRAINT contracts_client_id_fkey FOREIGN KEY (client_id) REFERENCES users(id),
    ADD CONSTRAINT contracts_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES users(id),
    ADD CONSTRAINT contracts_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES bookings(id);


-- Fix structure of 'payments' table
ALTER TABLE payments
    ADD COLUMN IF NOT EXISTS payment_status_id integer,
    ADD COLUMN IF NOT EXISTS created_by uuid,
    ADD COLUMN IF NOT EXISTS notes text;

-- Add Foreign Key Constraints for payments
ALTER TABLE payments
    ADD CONSTRAINT payments_payment_status_id_fkey FOREIGN KEY (payment_status_id) REFERENCES payment_statuses(id),
    ADD CONSTRAINT payments_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);

-- Optional: Drop 'status' from payments if it conflicts or is unused
-- ALTER TABLE payments DROP COLUMN status;
